package com.api.generator.runtime.validation;

import com.api.generator.runtime.error.ValidationError;
import com.api.generator.runtime.schema.SchemaRegistry;
import com.api.generator.runtime.schema.SqlTypeMapper;
import com.api.generator.schema.ColumnInfo;
import com.api.generator.schema.TableInfo;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public class SchemaValidator {

    private final SchemaRegistry registry;

    public SchemaValidator(SchemaRegistry registry) {
        this.registry = registry;
    }

    public List<ValidationError.FieldError> validateInsert(String tableName, Map<String, Object> body) {
        TableInfo table = registry.getTable(tableName).orElse(null);
        if (table == null) return List.of();

        List<ValidationError.FieldError> errors = new ArrayList<>();
        Set<String> knownCols = knownColumns(table);

        for (String key : body.keySet()) {
            if (!knownCols.contains(key.toLowerCase(Locale.ROOT))) {
                errors.add(new ValidationError.FieldError(key, body.get(key), "Unknown column '" + key + "'"));
            }
        }

        for (ColumnInfo col : table.getColumns()) {
            if (!col.isNullable() && !col.isAutoIncrement() && col.getDefaultValue() == null
                    && !body.containsKey(col.getName())) {
                if (table.getPrimaryKeys().contains(col.getName()) && isAutoGenerated(col)) {
                    continue;
                }
                errors.add(new ValidationError.FieldError(
                        col.getName(), null, "Required field '" + col.getName() + "' is missing"));
            }
        }

        validateValues(table, body, errors);
        return errors;
    }

    public List<ValidationError.FieldError> validateUpdate(String tableName, Map<String, Object> body) {
        TableInfo table = registry.getTable(tableName).orElse(null);
        if (table == null) return List.of();

        List<ValidationError.FieldError> errors = new ArrayList<>();
        Set<String> knownCols = knownColumns(table);

        for (String key : body.keySet()) {
            if (!knownCols.contains(key.toLowerCase(Locale.ROOT))) {
                errors.add(new ValidationError.FieldError(key, body.get(key), "Unknown column '" + key + "'"));
            }
        }

        validateValues(table, body, errors);
        return errors;
    }

    private Set<String> knownColumns(TableInfo table) {
        Set<String> knownCols = new HashSet<>();
        for (ColumnInfo c : table.getColumns()) {
            knownCols.add(c.getName().toLowerCase(Locale.ROOT));
        }
        return knownCols;
    }

    private void validateValues(TableInfo table, Map<String, Object> body, List<ValidationError.FieldError> errors) {
        for (Map.Entry<String, Object> entry : body.entrySet()) {
            String colName = entry.getKey();
            Object value = entry.getValue();

            ColumnInfo col = table.getColumns().stream()
                    .filter(c -> c.getName().equalsIgnoreCase(colName))
                    .findFirst()
                    .orElse(null);

            if (col == null || value == null) continue;

            try {
                SqlTypeMapper.convertValue(col, value);
            } catch (Exception e) {
                errors.add(new ValidationError.FieldError(
                        colName, value, "Invalid type for column '" + colName + "': " + e.getMessage()));
                continue;
            }

            if (col.getSize() > 0 && value instanceof String s) {
                String normalized = col.getJdbcType().toLowerCase(Locale.ROOT);
                if ((normalized.contains("varchar") || normalized.contains("char")) && s.length() > col.getSize()) {
                    errors.add(new ValidationError.FieldError(
                            colName, value, "Value exceeds maximum length of " + col.getSize()));
                }
            }

            if (col.isEnumType() && col.getEnumValues() != null && col.getEnumValues().length > 0) {
                String sVal = value.toString();
                boolean valid = List.of(col.getEnumValues()).contains(sVal);
                if (!valid) {
                    errors.add(new ValidationError.FieldError(
                            colName, value, "Value must be one of: " + String.join(", ", col.getEnumValues())));
                }
            }
        }
    }

    private boolean isAutoGenerated(ColumnInfo col) {
        String type = col.getJdbcType().toLowerCase(Locale.ROOT);
        return type.contains("serial") || type.contains("identity");
    }
}
