export const docsContent = {
  fr: {
    title: 'Documentation',
    subtitle: 'Guide pratique pour creer, tester et recuperer une API generee.',
    action: 'Nouvelle generation',
    overviewTitle: 'Centre d aide',
    overviewText: 'Commence par la section qui correspond a ton objectif. Chaque bloc explique quoi faire, quoi verifier et comment corriger les erreurs les plus courantes.',
    overviewCards: [
      ['Demarrer', 'Comprendre le parcours complet avant la premiere generation.', 'get-started'],
      ['Generer', 'Remplir le formulaire et lancer une API.', 'generate-api'],
      ['Tester et corriger', 'Utiliser preview, Swagger et les solutions rapides.', 'preview-api'],
    ],
    summaryTitle: 'Navigation',
    summaryText: 'Utilise ce menu pour aller directement a la bonne section.',
    summarySelectLabel: 'Aller a une section',
    summaryPlaceholder: 'Choisir une section',
    quickSummaryLabel: 'Resume rapide',
    errorSeenLabel: 'Ce que tu vois :',
    errorWhyLabel: 'Pourquoi :',
    errorFixLabel: 'Que faire :',
    sections: [
      {
        id: 'get-started',
        title: 'Bien demarrer',
        summary: 'API Generator transforme les informations de ton projet et de ta base en backend Spring Boot. Tout se pilote depuis le dashboard.',
        whenTitle: 'Quand utiliser cette section ?',
        whenItems: ['Tu decouvres la plateforme.', 'Tu veux comprendre le parcours avant de remplir le formulaire.'],
        beforeTitle: 'Avant de commencer',
        beforeItems: ['Avoir un compte et etre connecte.', 'Avoir App name, Base package, Database, JDBC URL, Schema, Username et Password.'],
        stepsTitle: 'Etapes',
        steps: ['Connecte-toi.', 'Ouvre Generations.', 'Prepare les informations du projet.', 'Lance une premiere generation.'],
        screenshot: '[Screenshot: Dashboard puis page Generations]',
        nextTitle: 'Ce qui se passe ensuite',
        nextItems: ['Une generation apparait dans l historique.', 'Les statuts et les logs deviennent visibles.', 'Tu peux ensuite ouvrir preview ou ZIP.'],
        tipsTitle: 'Conseils',
        tips: ['Commence avec un schema de test.', 'Utilise des noms de projet clairs.'],
        errorsTitle: 'Erreurs frequentes',
        errors: [
          { title: 'Connexion impossible', seen: 'Invalid credentials', why: 'Les identifiants sont incorrects.', fix: 'Verifie l email, l identifiant ou le mot de passe.' },
          { title: 'Email non verifie', seen: 'Verify your email before signing in', why: 'Le compte existe mais n est pas encore valide.', fix: 'Ouvre l email de verification puis reconnecte-toi.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Dois-je rester sur la page ?', answer: 'Non. Tout reste dans ton historique.' }],
      },
      {
        id: 'generate-api',
        title: 'Generer une API',
        summary: 'Le formulaire de generation cree un projet Spring Boot a partir de tes informations projet et base source.',
        whenTitle: 'Quand utiliser cette section ?',
        whenItems: ['Tu veux creer une nouvelle API.', 'Tu veux obtenir un projet telechargeable.'],
        beforeTitle: 'Avant de commencer',
        beforeItems: ['Verifier l URL JDBC.', 'Verifier le schema et les identifiants de base.', 'Choisir un nom de projet clair.'],
        stepsTitle: 'Etapes',
        steps: ['Renseigne App name.', 'Renseigne Base package.', 'Choisis Database.', 'Colle JDBC URL.', 'Renseigne Schema, Username et Password.', 'Clique sur Generer.'],
        screenshot: '[Screenshot: Formulaire de generation complet]',
        nextTitle: 'Ce qui se passe ensuite',
        nextItems: ['Le projet entre dans l historique.', 'Le statut evolue pendant le traitement.', 'Les logs deviennent consultables.'],
        tipsTitle: 'Conseils',
        tips: ['Teste une seule generation avant de lancer plusieurs variantes.', 'Relis les champs avant de cliquer sur Generer.'],
        errorsTitle: 'Erreurs frequentes',
        errors: [
          { title: 'Nom invalide', seen: 'Invalid application name', why: 'Le nom ne respecte pas le format attendu.', fix: 'Utilise un nom qui commence par une lettre et contient seulement des lettres ou chiffres.' },
          { title: 'Package invalide', seen: 'Invalid package name', why: 'Le package Java n est pas valide.', fix: 'Utilise des segments en minuscules separes par des points.' },
          { title: 'Quota depasse', seen: 'Monthly generation quota exceeded', why: 'La limite du plan a ete atteinte.', fix: 'Attends le prochain reset ou utilise un plan qui autorise plus de generations.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Puis-je quitter la page pendant la generation ?', answer: 'Oui. Reviens plus tard et retrouve le projet dans l historique.' }],
      },
      {
        id: 'preview-api',
        title: 'Previsualiser et tester',
        summary: 'La preview permet de lancer l API generee, d ouvrir Swagger et de verifier le resultat avant telechargement.',
        whenTitle: 'Quand utiliser cette section ?',
        whenItems: ['Tu veux tester les endpoints.', 'Tu veux verifier le resultat avant de recuperer le ZIP.'],
        beforeTitle: 'Avant de commencer',
        beforeItems: ['Attendre la fin de la generation.', 'Ouvrir la bonne entree dans l historique.'],
        stepsTitle: 'Etapes',
        steps: ['Clique sur Start Preview.', 'Attends que le statut soit actif.', 'Ouvre Swagger ou Swagger Proxy.', 'Teste les endpoints utiles.', 'Clique sur Stop Preview quand tu as termine.'],
        screenshot: '[Screenshot: Bloc preview avec URL et bouton Swagger]',
        nextTitle: 'Ce qui se passe ensuite',
        nextItems: ['Le dashboard affiche le statut de preview.', 'Swagger devient accessible quand la preview est prete.', 'Les logs restent visibles.', 'En cas d echec, les diagnostics hote et preview restent consultables dans Generations puis dans Overview.'],
        tipsTitle: 'Conseils',
        tips: ['Attends RUNNING avant d ouvrir Swagger.', 'Relance la preview si tu soupconnes un probleme temporaire.', 'Si la preview echoue, ouvre les checks hote avant de relancer pour verifier Docker ou Maven.'],
        errorsTitle: 'Erreurs frequentes',
        errors: [
          { title: 'Preview trop tot', seen: 'Preview is only available after generation is done', why: 'La generation n est pas terminee.', fix: 'Attends la fin du traitement puis reessaie.' },
          { title: 'Preview indisponible', seen: 'Preview configuration is not available', why: 'La preview ne peut pas demarrer pour cette generation.', fix: 'Verifie que la generation est complete. Si besoin, relance une nouvelle generation.' },
          { title: 'Diagnostic hote en echec', seen: 'Container runtime not reachable ou Maven unavailable', why: 'La machine du manager n est pas prete a reconstruire ou lancer la preview.', fix: 'Lis Host diagnostics dans Generations, demarre Docker ou Podman, puis verifie Maven avant une nouvelle tentative.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Ou trouver Swagger ?', answer: 'Depuis la zone preview de la page Generations.' }],
      },
      {
        id: 'download-projects',
        title: 'Telecharger le projet',
        summary: 'Quand l API est prete, tu peux recuperer le backend genere au format ZIP tout en gardant l historique dans le dashboard.',
        whenTitle: 'Quand utiliser cette section ?',
        whenItems: ['Tu veux recuperer le projet Spring Boot.', 'Tu veux archiver ou comparer plusieurs versions.'],
        beforeTitle: 'Avant de commencer',
        beforeItems: ['Attendre que la generation soit terminee.', 'Verifier que le ZIP est disponible pour ton compte.'],
        stepsTitle: 'Etapes',
        steps: ['Trouve le projet dans Generations.', 'Verifie que le statut est termine.', 'Clique sur ZIP.', 'Enregistre le fichier sur ton ordinateur.'],
        screenshot: '[Screenshot: Historique avec action ZIP]',
        nextTitle: 'Ce qui se passe ensuite',
        nextItems: ['Le fichier ZIP est telecharge.', 'Le projet reste visible dans l historique.'],
        tipsTitle: 'Conseils',
        tips: ['Renomme localement les ZIP si tu gardes plusieurs versions.', 'Teste la preview avant telechargement si tu veux plus de confiance.'],
        errorsTitle: 'Erreurs frequentes',
        errors: [
          { title: 'ZIP pas pret', seen: 'The ZIP is not available for this job yet', why: 'La generation n est pas encore finie.', fix: 'Attends la fin de la generation puis reessaie.' },
          { title: 'ZIP limite', seen: 'ZIP can be downloaded once per generated API', why: 'Le telechargement est limite par le plan ou le quota.', fix: 'Verifie les regles du compte ou utilise une autre generation eligibile.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Le projet disparait-il apres telechargement ?', answer: 'Non. Il reste dans l historique.' }],
      },
      {
        id: 'common-errors',
        title: 'Erreurs frequentes et corrections',
        summary: 'Quand une action echoue ou reste grisee, commence par verifier le statut actuel et utilise cette section pour trouver la bonne correction.',
        whenTitle: 'Quand utiliser cette section ?',
        whenItems: ['Un bouton est grise.', 'La preview ne demarre pas.', 'Le telechargement ne fonctionne pas.'],
        beforeTitle: 'Avant de commencer',
        beforeItems: ['Garde le message exact sous les yeux.', 'Note le projet et son statut courant.'],
        stepsTitle: 'Etapes',
        steps: ['Lis le message d erreur complet.', 'Verifie le statut de generation ou preview.', 'Rafraichis une fois la page.', 'Reessaie ensuite l action appropriee.'],
        screenshot: '[Screenshot: Zone de message d erreur dans Generations]',
        nextTitle: 'Ce qui se passe ensuite',
        nextItems: ['L action redevient disponible, ou', 'tu identifies le champ a corriger, ou', 'tu retrouves deja le projet dans l historique.', 'Si une preview a deja echoue, Overview affiche aussi un resume pour repartir plus vite.'],
        tipsTitle: 'Conseils',
        tips: ['Ne reclique pas plusieurs fois sans verifier le statut.', 'Corrige d abord les erreurs de formulaire.', 'Utilise Overview pour repérer rapidement les previews en echec recentes avant de rouvrir Generations.'],
        errorsTitle: 'Erreurs frequentes',
        errors: [
          { title: 'Action desactivee', seen: 'Bouton Preview ou ZIP grise', why: 'L action depend du statut courant ou du plan.', fix: 'Verifie que la generation est terminee et que ton compte autorise cette action.' },
          { title: 'Job indisponible', seen: 'This job is no longer available on this server', why: 'Le suivi live n est plus disponible.', fix: 'Rafraichis le dashboard et utilise l historique persistant.' },
          { title: 'Preview en echec recent', seen: 'Carte Failed previews dans Overview', why: 'Une preview recente a echoue et demande une investigation avant redemarrage.', fix: 'Ouvre Generations depuis le lien Investigate pour lire error hint, host diagnostics et l action recommandee.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Dois-je regenerer tout de suite ?', answer: 'Pas toujours. Verifie d abord les logs et l historique.' }],
      },
    ],
  },
  en: {
    title: 'Documentation',
    subtitle: 'Practical guide to create, test, and download a generated API.',
    action: 'New generation',
    overviewTitle: 'Help center',
    overviewText: 'Start with the section that matches your goal. Each block explains what to do, what to check, and how to fix the most common issues.',
    overviewCards: [
      ['Get started', 'Understand the full flow before your first generation.', 'get-started'],
      ['Generate', 'Fill in the form and create an API.', 'generate-api'],
      ['Test and fix', 'Use preview, Swagger, and quick fixes.', 'preview-api'],
    ],
    summaryTitle: 'Navigation',
    summaryText: 'Use this menu to jump directly to the section you need.',
    summarySelectLabel: 'Go to a section',
    summaryPlaceholder: 'Choose a section',
    quickSummaryLabel: 'Quick summary',
    errorSeenLabel: 'What you see:',
    errorWhyLabel: 'Why it happens:',
    errorFixLabel: 'How to fix it:',
    sections: [
      {
        id: 'get-started',
        title: 'Get started',
        summary: 'API Generator turns your project and database details into a Spring Boot backend. Everything is managed from the dashboard.',
        whenTitle: 'When should you use this section?',
        whenItems: ['You are new to the platform.', 'You want to understand the flow before filling in the form.'],
        beforeTitle: 'Before you start',
        beforeItems: ['Have an account and sign in.', 'Prepare App name, Base package, Database, JDBC URL, Schema, Username, and Password.'],
        stepsTitle: 'Steps',
        steps: ['Sign in.', 'Open Generations.', 'Prepare the project details.', 'Start your first generation.'],
        screenshot: '[Screenshot: Dashboard and Generations page]',
        nextTitle: 'What happens next',
        nextItems: ['A new generation appears in history.', 'Status and logs become visible.', 'You can then open preview or ZIP.'],
        tipsTitle: 'Tips',
        tips: ['Start with a test schema.', 'Use clear project names.'],
        errorsTitle: 'Common errors',
        errors: [
          { title: 'Unable to sign in', seen: 'Invalid credentials', why: 'The credentials are incorrect.', fix: 'Check the email, username, or password.' },
          { title: 'Email not verified', seen: 'Verify your email before signing in', why: 'The account exists but is not validated yet.', fix: 'Open the verification email and sign in again.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Do I need to stay on the page?', answer: 'No. Everything stays in your history.' }],
      },
      {
        id: 'generate-api',
        title: 'Generate an API',
        summary: 'The generation form creates a Spring Boot project from your project settings and source database.',
        whenTitle: 'When should you use this section?',
        whenItems: ['You want to create a new API.', 'You want a downloadable project.'],
        beforeTitle: 'Before you start',
        beforeItems: ['Check the JDBC URL.', 'Check the schema and database credentials.', 'Choose a clear project name.'],
        stepsTitle: 'Steps',
        steps: ['Enter App name.', 'Enter Base package.', 'Choose Database.', 'Paste JDBC URL.', 'Enter Schema, Username, and Password.', 'Click Generate.'],
        screenshot: '[Screenshot: Completed generation form]',
        nextTitle: 'What happens next',
        nextItems: ['The project enters history.', 'The status changes during processing.', 'Logs become available.'],
        tipsTitle: 'Tips',
        tips: ['Test one generation before creating many variants.', 'Review the fields before you click Generate.'],
        errorsTitle: 'Common errors',
        errors: [
          { title: 'Invalid name', seen: 'Invalid application name', why: 'The name format is not accepted.', fix: 'Use a name that starts with a letter and contains only letters or numbers.' },
          { title: 'Invalid package', seen: 'Invalid package name', why: 'The Java package is not valid.', fix: 'Use lowercase segments separated by dots.' },
          { title: 'Quota reached', seen: 'Monthly generation quota exceeded', why: 'Your plan limit has been reached.', fix: 'Wait for the reset or use a plan that allows more generations.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Can I leave the page during generation?', answer: 'Yes. Come back later and find the project in history.' }],
      },
      {
        id: 'preview-api',
        title: 'Preview and test',
        summary: 'Preview lets you start the generated API, open Swagger, and validate the result before downloading it.',
        whenTitle: 'When should you use this section?',
        whenItems: ['You want to test endpoints.', 'You want to verify the result before you download the ZIP.'],
        beforeTitle: 'Before you start',
        beforeItems: ['Wait until generation is complete.', 'Open the correct item in history.'],
        stepsTitle: 'Steps',
        steps: ['Click Start Preview.', 'Wait until the status is active.', 'Open Swagger or Swagger Proxy.', 'Test the endpoints you need.', 'Click Stop Preview when you are done.'],
        screenshot: '[Screenshot: Preview block with URL and Swagger button]',
        nextTitle: 'What happens next',
        nextItems: ['The dashboard shows the preview status.', 'Swagger becomes available when preview is ready.', 'Logs stay visible.', 'If preview fails, host and preview diagnostics stay visible in Generations and are surfaced again in Overview.'],
        tipsTitle: 'Tips',
        tips: ['Wait for RUNNING before opening Swagger.', 'Restart preview if you suspect a temporary issue.', 'If preview fails, inspect host checks before retrying so Docker or Maven issues are fixed first.'],
        errorsTitle: 'Common errors',
        errors: [
          { title: 'Preview started too early', seen: 'Preview is only available after generation is done', why: 'Generation is not finished yet.', fix: 'Wait for processing to finish, then try again.' },
          { title: 'Preview unavailable', seen: 'Preview configuration is not available', why: 'Preview cannot start for this generation.', fix: 'Check that generation completed successfully. If needed, start a new generation.' },
          { title: 'Host diagnostics failing', seen: 'Container runtime not reachable or Maven unavailable', why: 'The manager host is not ready to rebuild or launch the preview.', fix: 'Read Host diagnostics in Generations, start Docker or Podman, and verify Maven before trying again.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Where can I find Swagger?', answer: 'From the preview area in the Generations page.' }],
      },
      {
        id: 'download-projects',
        title: 'Download the project',
        summary: 'When the API is ready, you can download the generated backend as a ZIP file while keeping the full history in the dashboard.',
        whenTitle: 'When should you use this section?',
        whenItems: ['You want to retrieve the Spring Boot project.', 'You want to archive or compare several versions.'],
        beforeTitle: 'Before you start',
        beforeItems: ['Wait until generation is complete.', 'Make sure ZIP is available for your account.'],
        stepsTitle: 'Steps',
        steps: ['Find the project in Generations.', 'Confirm the status is complete.', 'Click ZIP.', 'Save the file to your computer.'],
        screenshot: '[Screenshot: History with ZIP action]',
        nextTitle: 'What happens next',
        nextItems: ['The ZIP file downloads.', 'The project stays visible in history.'],
        tipsTitle: 'Tips',
        tips: ['Rename ZIP files locally if you keep many versions.', 'Test preview before download if you want extra confidence.'],
        errorsTitle: 'Common errors',
        errors: [
          { title: 'ZIP not ready', seen: 'The ZIP is not available for this job yet', why: 'Generation is not finished yet.', fix: 'Wait until generation completes, then try again.' },
          { title: 'ZIP limited', seen: 'ZIP can be downloaded once per generated API', why: 'Download is limited by your plan or quota.', fix: 'Check account limits or use another eligible generation.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Does the project disappear after download?', answer: 'No. It stays in history.' }],
      },
      {
        id: 'common-errors',
        title: 'Common errors and fixes',
        summary: 'When an action fails or stays disabled, start by checking the current status and use this section to find the correct next step.',
        whenTitle: 'When should you use this section?',
        whenItems: ['A button is disabled.', 'Preview does not start.', 'Download does not work.'],
        beforeTitle: 'Before you start',
        beforeItems: ['Keep the exact message visible.', 'Note the project and its current status.'],
        stepsTitle: 'Steps',
        steps: ['Read the full error message.', 'Check the generation or preview status.', 'Refresh the page once.', 'Try the correct action again.'],
        screenshot: '[Screenshot: Error message area in Generations]',
        nextTitle: 'What happens next',
        nextItems: ['The action becomes available again, or', 'you identify the field to correct, or', 'you find the project already saved in history.', 'If a preview already failed, Overview also surfaces a short summary to restart the investigation faster.'],
        tipsTitle: 'Tips',
        tips: ['Do not retry many times without checking status.', 'Fix form errors first.', 'Use Overview to spot recent failed previews before reopening Generations.'],
        errorsTitle: 'Common errors',
        errors: [
          { title: 'Disabled action', seen: 'A disabled Preview or ZIP button', why: 'The action depends on the current status or your plan.', fix: 'Check that generation is complete and that your account allows the action.' },
          { title: 'Job unavailable', seen: 'This job is no longer available on this server', why: 'Live tracking is no longer available.', fix: 'Refresh the dashboard and use the persistent history.' },
          { title: 'Recent preview failure', seen: 'Failed previews card in Overview', why: 'A recent preview failed and should be investigated before restart.', fix: 'Open Generations from the Investigate link to inspect the error hint, host diagnostics, and recommended action.' },
        ],
        faqTitle: 'FAQ',
        faq: [{ question: 'Should I regenerate right away?', answer: 'Not always. Check logs and history first.' }],
      },
    ],
  },
} as const
