package com.api.generator.runtime.web;

import com.api.generator.runtime.jdbc.DynamicRepository;
import com.api.generator.runtime.jdbc.SqlBuilder;
import com.api.generator.runtime.schema.ApiManifest;
import com.api.generator.runtime.schema.ManifestRegistry;
import com.api.generator.runtime.schema.Operation;
import com.api.generator.runtime.schema.SchemaRegistry;
import com.api.generator.runtime.schema.TableManifest;
import com.api.generator.runtime.validation.SchemaValidator;
import com.api.generator.schema.ColumnInfo;
import com.api.generator.schema.ColumnRole;
import com.api.generator.schema.DatabaseType;
import com.api.generator.schema.TableInfo;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.web.MockHttpServletRequest;

import javax.sql.DataSource;
import java.util.List;
import java.util.Map;
import java.util.EnumSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class DynamicCrudControllerTest {

    private DynamicCrudController controller;
    private DynamicRepository repository;
    private SchemaRegistry registry;
    private SchemaValidator validator;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:runtime_crud_" + System.nanoTime() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        NamedParameterJdbcTemplate jdbc = new NamedParameterJdbcTemplate(dataSource);
        jdbc.getJdbcTemplate().execute("""
                create table books (
                    id bigint generated by default as identity primary key,
                    title varchar(120) not null,
                    pages integer,
                    deleted_at timestamp
                )
                """);

        registry = new SchemaRegistry();
        registry.register(List.of(booksTable()));
        repository = new DynamicRepository(jdbc, new SqlBuilder(DatabaseType.POSTGRESQL), registry);
        validator = new SchemaValidator(registry);
        controller = new DynamicCrudController(
                repository,
                registry,
                validator,
                new ManifestRegistry()
        );
    }

    @Test
    void performsCrudAndFiltersSoftDeletedRows() {
        var createResponse = controller.create("books", mutable("title", "Kindred", "pages", 264), request("/api/books"));
        assertEquals(HttpStatus.CREATED, createResponse.getStatusCode());
        Map<?, ?> created = (Map<?, ?>) createResponse.getBody();
        assertNotNull(created);
        Object id = created.get("id");

        var listResponse = controller.list("books", 0, 20, "title", request("/api/books"));
        PageResponse page = (PageResponse) listResponse.getBody();
        assertNotNull(page);
        assertEquals(1, page.totalElements());
        assertEquals("Kindred", page.content().get(0).get("title"));

        var getResponse = controller.getById("books", id.toString());
        assertEquals("Kindred", ((Map<?, ?>) getResponse.getBody()).get("title"));

        var updateResponse = controller.update("books", id.toString(), mutable("title", "Kindred II", "pages", 265), request("/api/books/" + id));
        assertEquals("Kindred II", ((Map<?, ?>) updateResponse.getBody()).get("title"));

        var deleteResponse = controller.delete("books", id.toString());
        assertEquals(HttpStatus.NO_CONTENT, deleteResponse.getStatusCode());

        PageResponse afterDelete = (PageResponse) controller.list("books", 0, 20, null, request("/api/books")).getBody();
        assertNotNull(afterDelete);
        assertEquals(0, afterDelete.totalElements());
    }

    @Test
    void rejectsValidationErrorsBeforeInsert() {
        var response = controller.create("books", mutable("unknown", "value"), request("/api/books"));

        assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
    }

    @Test
    void rejectsUnknownTables() {
        assertThrows(RuntimeException.class, () -> controller.getById("missing", "1"));
    }

    @Test
    void handlesPagingSortingAndMissingRows() {
        controller.create("books", mutable("title", "A", "pages", 10), request("/api/books"));
        controller.create("books", mutable("title", "B", "pages", 20), request("/api/books"));

        PageResponse page = (PageResponse) controller.list("books", -1, 500, "-title", request("/api/books")).getBody();
        assertNotNull(page);
        assertEquals(0, page.page());
        assertEquals(100, page.size());
        assertEquals("B", page.content().get(0).get("title"));

        assertThrows(RuntimeException.class, () -> controller.getById("books", "999"));
        assertThrows(RuntimeException.class, () -> controller.update("books", "999", mutable("title", "Missing"), request("/api/books/999")));
        assertThrows(RuntimeException.class, () -> controller.delete("books", "999"));
    }

    @Test
    void honorsManifestDeniedOperationsAndInvalidPrimaryKeyShape() {
        ManifestRegistry manifest = new ManifestRegistry();
        TableManifest books = new TableManifest();
        books.setOperations(EnumSet.of(Operation.LIST));
        ApiManifest apiManifest = new ApiManifest();
        apiManifest.setTables(Map.of("books", books));
        manifest.register(apiManifest);
        DynamicCrudController restricted = new DynamicCrudController(repository, registry, validator, manifest);

        assertEquals(HttpStatus.METHOD_NOT_ALLOWED, restricted.create("books", mutable("title", "Denied"), request("/api/books")).getStatusCode());
        assertEquals(HttpStatus.METHOD_NOT_ALLOWED, restricted.getById("books", "1").getStatusCode());
        assertEquals(HttpStatus.METHOD_NOT_ALLOWED, restricted.update("books", "1", mutable("title", "Denied"), request("/api/books/1")).getStatusCode());
        assertEquals(HttpStatus.METHOD_NOT_ALLOWED, restricted.delete("books", "1").getStatusCode());
        assertEquals(HttpStatus.OK, restricted.list("books", 0, 20, null, request("/api/books")).getStatusCode());

        assertThrows(IllegalArgumentException.class, () -> controller.getById("books", "1,2"));
    }

    @Test
    void canDenyListOperationFromManifest() {
        ManifestRegistry manifest = new ManifestRegistry();
        TableManifest books = new TableManifest();
        books.setOperations(EnumSet.noneOf(Operation.class));
        ApiManifest apiManifest = new ApiManifest();
        apiManifest.setTables(Map.of("books", books));
        manifest.register(apiManifest);
        DynamicCrudController restricted = new DynamicCrudController(repository, registry, validator, manifest);

        assertEquals(HttpStatus.METHOD_NOT_ALLOWED, restricted.list("books", 0, 20, null, request("/api/books")).getStatusCode());
    }

    private static TableInfo booksTable() {
        TableInfo table = new TableInfo("books");
        table.getPrimaryKeys().add("id");
        table.getColumns().add(ColumnInfo.builder().name("id").jdbcType("BIGINT").nullable(false).autoIncrement(true).build());
        table.getColumns().add(ColumnInfo.builder().name("title").jdbcType("VARCHAR").size(120).nullable(false).build());
        table.getColumns().add(ColumnInfo.builder().name("pages").jdbcType("INTEGER").nullable(true).build());
        table.getColumns().add(ColumnInfo.builder().name("deleted_at").jdbcType("TIMESTAMP").nullable(true).role(ColumnRole.SOFT_DELETE).build());
        return table;
    }

    private static MockHttpServletRequest request(String path) {
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.setRequestURI(path);
        return request;
    }

    private static Map<String, Object> mutable(Object... entries) {
        Map<String, Object> map = new java.util.LinkedHashMap<>();
        for (int i = 0; i < entries.length; i += 2) {
            map.put((String) entries[i], entries[i + 1]);
        }
        return map;
    }
}
