create table organizations (
    id bigint generated by default as identity primary key,
    slug varchar(80) not null unique,
    name varchar(180) not null,
    billing_email varchar(180) not null,
    plan_code varchar(30) default 'FREE' not null,
    seat_limit integer default 3 not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null
);

create table users (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    email varchar(180) not null unique,
    display_name varchar(140) not null,
    role_code varchar(30) default 'MEMBER' not null,
    active boolean default true not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint fk_users_organization foreign key (organization_id) references organizations(id)
);

create table projects (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    owner_user_id bigint not null,
    code varchar(60) not null,
    name varchar(180) not null,
    description varchar(1000),
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint uq_projects_org_code unique (organization_id, code),
    constraint fk_projects_organization foreign key (organization_id) references organizations(id),
    constraint fk_projects_owner foreign key (owner_user_id) references users(id)
);

create table environments (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name varchar(80) not null,
    base_url varchar(300),
    sort_order integer default 0 not null,
    created_at timestamp default current_timestamp not null,
    constraint uq_environments_project_name unique (project_id, name),
    constraint fk_environments_project foreign key (project_id) references projects(id)
);

create table api_keys (
    id bigint generated by default as identity primary key,
    environment_id bigint not null,
    key_name varchar(120) not null,
    key_hash varchar(120) not null unique,
    scopes varchar(300) not null,
    expires_at timestamp,
    revoked_at timestamp,
    created_at timestamp default current_timestamp not null,
    constraint fk_api_keys_environment foreign key (environment_id) references environments(id)
);

create table tickets (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    reporter_user_id bigint not null,
    assignee_user_id bigint,
    public_ref varchar(40) not null unique,
    title varchar(220) not null,
    priority varchar(20) default 'MEDIUM' not null,
    status varchar(20) default 'OPEN' not null,
    estimate_points numeric(5, 2),
    due_on date,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp default current_timestamp not null,
    constraint fk_tickets_project foreign key (project_id) references projects(id),
    constraint fk_tickets_reporter foreign key (reporter_user_id) references users(id),
    constraint fk_tickets_assignee foreign key (assignee_user_id) references users(id)
);

create index idx_tickets_project_status on tickets(project_id, status);
create index idx_tickets_assignee_due on tickets(assignee_user_id, due_on);

create table ticket_comments (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    author_user_id bigint not null,
    body varchar(2000) not null,
    internal_note boolean default false not null,
    created_at timestamp default current_timestamp not null,
    constraint fk_ticket_comments_ticket foreign key (ticket_id) references tickets(id),
    constraint fk_ticket_comments_author foreign key (author_user_id) references users(id)
);

create table labels (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    code varchar(60) not null,
    label varchar(120) not null,
    color varchar(7) not null,
    constraint uq_labels_org_code unique (organization_id, code),
    constraint fk_labels_organization foreign key (organization_id) references organizations(id)
);

create table ticket_labels (
    ticket_id bigint not null,
    label_id bigint not null,
    added_by_user_id bigint not null,
    added_at timestamp default current_timestamp not null,
    primary key (ticket_id, label_id),
    constraint fk_ticket_labels_ticket foreign key (ticket_id) references tickets(id),
    constraint fk_ticket_labels_label foreign key (label_id) references labels(id),
    constraint fk_ticket_labels_user foreign key (added_by_user_id) references users(id)
);

create table deployment_events (
    id bigint generated by default as identity primary key,
    environment_id bigint not null,
    deployed_by_user_id bigint not null,
    version_tag varchar(80) not null,
    status varchar(30) not null,
    duration_ms bigint,
    metadata clob,
    created_at timestamp default current_timestamp not null,
    constraint fk_deployment_events_environment foreign key (environment_id) references environments(id),
    constraint fk_deployment_events_user foreign key (deployed_by_user_id) references users(id)
);
