create table customers (
    id bigint generated by default as identity primary key,
    email varchar(180) not null unique,
    full_name varchar(160) not null,
    risk_score integer not null,
    created_at timestamp default current_timestamp not null
);

create table orders (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    public_ref varchar(40) not null unique,
    status varchar(20) not null,
    total_amount numeric(10, 2) not null,
    placed_at timestamp default current_timestamp not null,
    constraint fk_orders_customer foreign key (customer_id) references customers(id)
);

create table order_lines (
    order_id bigint not null,
    line_no integer not null,
    sku varchar(80) not null,
    quantity integer not null,
    unit_price numeric(10, 2) not null,
    primary key (order_id, line_no),
    constraint fk_order_lines_order foreign key (order_id) references orders(id)
);
